# Generated by Django 4.1.7 on 2023-03-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='capa',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
